const express=require('express'),path=require('path'),fs=require('fs'),crypto=require('crypto'),multer=require('multer'),sharp=require('sharp'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),cookieParser=require('cookie-parser'),pkg=require('./package.json');
const {openDatabase}=require('./src/db'); const {ALLOWED_MIMES,hotspot:validateHotspot}=require('./src/validation');
function createApp(opts={}){const db=opts.db||openDatabase(),app=express(),imageDir=opts.imageDir||process.env.IMAGE_DIR||path.join(process.cwd(),'data','images'),secret=process.env.SESSION_SECRET||'development-only-change-me';fs.mkdirSync(imageDir,{recursive:true});app.disable('x-powered-by');if(process.env.TRUST_PROXY==='1')app.set('trust proxy',1);app.use(express.json({limit:'1mb'}));app.use(cookieParser());app.use((q,r,n)=>{r.set('X-Content-Type-Options','nosniff');r.set('Referrer-Policy','same-origin');n()});
 const updateRepo=process.env.UPDATE_REPO||'',updateDir=path.dirname(imageDir),updateStatusFile=path.join(updateDir,'update-status.json'),updateRequestFile=path.join(updateDir,'update-request.json');let releaseCache=null;
 const optionalAuth=(q,r,n)=>{try{const token=jwt.verify(q.cookies.maplens_session,secret);q.user=db.prepare('SELECT id,username,role FROM users WHERE id=?').get(token.id)||null}catch{q.user=null}n()};
 const auth=(q,r,n)=>optionalAuth(q,r,()=>q.user?n():r.status(401).json({error:'Anmeldung erforderlich'}));const adminOnly=(q,r,n)=>auth(q,r,()=>q.user.role==='admin'?n():r.status(403).json({error:'Adminrechte erforderlich'}));
 const canView=(imageId,user)=>!!db.prepare("SELECT 1 FROM images i WHERE i.id=? AND (i.visibility='public' OR EXISTS(SELECT 1 FROM image_viewers v WHERE v.image_id=i.id AND v.user_id=?) OR ?='admin')").get(imageId,user?.id||-1,user?.role||'');
 const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||20)*1048576},fileFilter:(q,f,cb)=>cb(null,ALLOWED_MIMES.has(f.mimetype))});
 const full=id=>{const h=db.prepare('SELECT h.*,c.name city,co.name country,con.name continent FROM hotspots h LEFT JOIN cities c ON c.id=h.city_id LEFT JOIN countries co ON co.code=h.country_code LEFT JOIN continents con ON con.code=h.continent_code WHERE h.id=?').get(id);if(h)h.links=db.prepare('SELECT id,title,url,description FROM hotspot_links WHERE hotspot_id=? ORDER BY id').all(id);return h};
 app.get('/api/status',(q,r)=>r.json({ok:true,version:pkg.version,adminExists:!!db.prepare('SELECT id FROM users LIMIT 1').get()}));
 app.post('/api/auth/setup',(q,r)=>{if(db.prepare('SELECT id FROM users LIMIT 1').get())return r.status(409).json({error:'Administrator existiert bereits'});if(!q.body.username?.trim()||String(q.body.password||'').length<10)return r.status(400).json({error:'Benutzername und mindestens 10 Zeichen Passwort erforderlich'});db.prepare("INSERT INTO users(username,password_hash,role) VALUES (?,?,'admin')").run(q.body.username.trim(),bcrypt.hashSync(q.body.password,12));r.status(201).json({ok:true})});
 const sessionCookie=q=>({httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE==='1'||(process.env.COOKIE_SECURE!=='0'&&q.secure),maxAge:43200000});
 app.post('/api/auth/login',(q,r)=>{const u=db.prepare('SELECT * FROM users WHERE username=?').get(q.body.username||'');if(!u||!bcrypt.compareSync(q.body.password||'',u.password_hash))return r.status(401).json({error:'Ungültige Zugangsdaten'});r.cookie('maplens_session',jwt.sign({id:u.id},secret,{expiresIn:'12h'}),sessionCookie(q));r.json({id:u.id,username:u.username,role:u.role})});
 app.post('/api/auth/logout',(q,r)=>{r.clearCookie('maplens_session');r.json({ok:true})});app.get('/api/auth/me',auth,(q,r)=>r.json(q.user));
 app.put('/api/auth/credentials',auth,(q,r)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(q.user.id);if(!u||!bcrypt.compareSync(String(q.body.current_password||''),u.password_hash))return r.status(400).json({error:'Aktuelles Passwort ist nicht korrekt'});const username=String(q.body.username||'').trim(),password=String(q.body.new_password||'');if(!username)return r.status(400).json({error:'Benutzername erforderlich'});if(password&&password.length<10)return r.status(400).json({error:'Neues Passwort muss mindestens 10 Zeichen haben'});if(db.prepare('SELECT id FROM users WHERE username=? AND id<>?').get(username,u.id))return r.status(409).json({error:'Benutzername ist bereits vergeben'});db.prepare('UPDATE users SET username=?,password_hash=? WHERE id=?').run(username,password?bcrypt.hashSync(password,12):u.password_hash,u.id);r.cookie('maplens_session',jwt.sign({id:u.id},secret,{expiresIn:'12h'}),sessionCookie(q));r.json({ok:true,id:u.id,username,role:u.role})});
 function newerVersion(candidate,current){const parse=value=>String(value).split('.').map(x=>Number(x)||0),a=parse(candidate),b=parse(current);for(let i=0;i<Math.max(a.length,b.length);i++){if((a[i]||0)!==(b[i]||0))return(a[i]||0)>(b[i]||0)}return false}
 async function latestRelease(force=false){if(!updateRepo)return{enabled:false,current_version:pkg.version};if(!force&&releaseCache&&Date.now()-releaseCache.time<900000)return releaseCache.value;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(`https://api.github.com/repos/${updateRepo}/releases/latest`,{headers:{Accept:'application/vnd.github+json','User-Agent':`MapLens/${pkg.version}`},signal:controller.signal});if(!response.ok)throw Error(response.status===404?'Noch kein Release veröffentlicht':`GitHub antwortet mit ${response.status}`);const release=await response.json(),version=String(release.tag_name||'').replace(/^v/,'');const value={enabled:true,current_version:pkg.version,latest_version:version,update_available:newerVersion(version,pkg.version),release_name:release.name||release.tag_name,release_url:release.html_url,published_at:release.published_at};releaseCache={time:Date.now(),value};return value}finally{clearTimeout(timer)}}
 app.get('/api/admin/update',adminOnly,async(q,r)=>{try{r.json(await latestRelease(q.query.force==='1'))}catch(e){r.status(502).json({error:`Updateprüfung fehlgeschlagen: ${e.message}`})}});
 app.get('/api/admin/update/status',adminOnly,(q,r)=>{try{r.json(JSON.parse(fs.readFileSync(updateStatusFile,'utf8')))}catch{r.json({state:'idle',current_version:pkg.version})}});
 app.post('/api/admin/update',adminOnly,async(q,r)=>{try{const release=await latestRelease(true);if(!release.enabled)return r.status(409).json({error:'Updates sind auf diesem Server nicht konfiguriert'});if(!release.update_available)return r.status(409).json({error:'MapLens ist bereits aktuell'});fs.mkdirSync(updateDir,{recursive:true});const request={requested_at:new Date().toISOString(),requested_by:q.user.username,version:release.latest_version},statusTemp=updateStatusFile+'.app.tmp';fs.writeFileSync(statusTemp,JSON.stringify({state:'queued',target_version:release.latest_version,updated_at:new Date().toISOString()}));fs.renameSync(statusTemp,updateStatusFile);const temp=updateRequestFile+'.tmp';fs.writeFileSync(temp,JSON.stringify(request));fs.renameSync(temp,updateRequestFile);r.status(202).json({ok:true,version:release.latest_version})}catch(e){r.status(502).json({error:`Update konnte nicht angefordert werden: ${e.message}`})}});
 app.get('/api/images',optionalAuth,(q,r)=>r.json(db.prepare("SELECT i.*,(SELECT COUNT(*) FROM hotspots h WHERE h.image_id=i.id) hotspot_count FROM images i WHERE i.visibility='public' OR EXISTS(SELECT 1 FROM image_viewers v WHERE v.image_id=i.id AND v.user_id=?) OR ?='admin' ORDER BY i.id DESC").all(q.user?.id||-1,q.user?.role||'')));
 app.get('/api/images/:id',optionalAuth,(q,r)=>{if(!canView(q.params.id,q.user))return r.status(404).json({error:'Bild nicht gefunden'});const i=db.prepare('SELECT * FROM images WHERE id=?').get(q.params.id);i.hotspots=db.prepare('SELECT id FROM hotspots WHERE image_id=?').all(i.id).map(x=>full(x.id));r.json(i)});
 app.get('/api/images/:id/file',optionalAuth,(q,r)=>{if(!canView(q.params.id,q.user))return r.sendStatus(404);const i=db.prepare('SELECT * FROM images WHERE id=?').get(q.params.id);r.type(i.mime_type).sendFile(path.resolve(imageDir,i.filename))});
 app.post('/api/images',adminOnly,upload.single('image'),async(q,r,n)=>{try{if(!q.file)return r.status(400).json({error:'Gültiges JPG, PNG oder WEBP erforderlich'});const m=await sharp(q.file.buffer).metadata();if(!m.width||!['jpeg','png','webp'].includes(m.format))return r.status(400).json({error:'Ungültige Bilddatei'});const ext={jpeg:'.jpg',png:'.png',webp:'.webp'}[m.format],filename=crypto.randomUUID()+ext;await sharp(q.file.buffer).rotate().toFile(path.join(imageDir,filename));const z=await sharp(path.join(imageDir,filename)).metadata(),out=db.prepare('INSERT INTO images(filename,original_name,title,description,width,height,mime_type) VALUES (?,?,?,?,?,?,?)').run(filename,path.basename(q.file.originalname),q.body.title?.trim()||path.parse(q.file.originalname).name,q.body.description||'',z.width,z.height,q.file.mimetype);r.status(201).json(db.prepare('SELECT * FROM images WHERE id=?').get(out.lastInsertRowid))}catch(e){n(e)}});
 app.put('/api/images/:id',adminOnly,(q,r)=>{const o=db.prepare('UPDATE images SET title=?,description=? WHERE id=?').run(String(q.body.title||'').trim(),String(q.body.description||''),q.params.id);if(!o.changes)return r.sendStatus(404);r.json({ok:true})});
 app.delete('/api/images/:id',adminOnly,(q,r)=>{const i=db.prepare('SELECT filename FROM images WHERE id=?').get(q.params.id);if(!i)return r.sendStatus(404);db.prepare('DELETE FROM images WHERE id=?').run(q.params.id);fs.rmSync(path.join(imageDir,i.filename),{force:true});r.json({ok:true})});
 app.get('/api/images/:id/hotspots',optionalAuth,(q,r)=>canView(q.params.id,q.user)?r.json(db.prepare('SELECT id FROM hotspots WHERE image_id=?').all(q.params.id).map(x=>full(x.id))):r.sendStatus(404));
 app.get('/api/map-hotspots',optionalAuth,(q,r)=>r.json(db.prepare("SELECT h.id,h.image_id,h.x,h.y,h.radius,h.latitude,h.longitude,h.color,h.title hotspot_title,h.short_description,i.title image_title FROM hotspots h JOIN images i ON i.id=h.image_id WHERE h.latitude IS NOT NULL AND h.longitude IS NOT NULL AND (i.visibility='public' OR EXISTS(SELECT 1 FROM image_viewers v WHERE v.image_id=i.id AND v.user_id=?) OR ?='admin') ORDER BY i.title,h.title").all(q.user?.id||-1,q.user?.role||'')));
 function save(imageId,id,body){const h=validateHotspot(body);return db.transaction(()=>{let hid=id;if(id){db.prepare('UPDATE hotspots SET x=?,y=?,radius=?,title=?,short_description=?,description=?,continent_code=?,country_code=?,city_id=?,latitude=?,longitude=?,map_zoom=?,location_name=?,color=?,label=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(h.x,h.y,h.radius,h.title,h.short_description,h.description,h.continent_code,h.country_code,h.city_id,h.latitude,h.longitude,h.map_zoom,h.location_name,h.color,h.label,id);db.prepare('DELETE FROM hotspot_links WHERE hotspot_id=?').run(id)}else hid=db.prepare('INSERT INTO hotspots(image_id,x,y,radius,title,short_description,description,continent_code,country_code,city_id,latitude,longitude,map_zoom,location_name,color,label) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(imageId,h.x,h.y,h.radius,h.title,h.short_description,h.description,h.continent_code,h.country_code,h.city_id,h.latitude,h.longitude,h.map_zoom,h.location_name,h.color,h.label).lastInsertRowid;const ins=db.prepare('INSERT INTO hotspot_links(hotspot_id,title,url,description) VALUES (?,?,?,?)');h.links.forEach(l=>ins.run(hid,l.title.trim(),l.url,l.description||''));return full(hid)})()}
 app.post('/api/images/:id/hotspots',adminOnly,(q,r)=>{try{if(!db.prepare('SELECT id FROM images WHERE id=?').get(q.params.id))return r.sendStatus(404);r.status(201).json(save(q.params.id,null,q.body))}catch(e){r.status(400).json({error:e.message})}});app.put('/api/hotspots/:id',adminOnly,(q,r)=>{const h=db.prepare('SELECT * FROM hotspots WHERE id=?').get(q.params.id);if(!h)return r.sendStatus(404);try{r.json(save(h.image_id,h.id,q.body))}catch(e){r.status(400).json({error:e.message})}});app.delete('/api/hotspots/:id',adminOnly,(q,r)=>{const o=db.prepare('DELETE FROM hotspots WHERE id=?').run(q.params.id);o.changes?r.json({ok:true}):r.sendStatus(404)});
 app.get('/api/continents',(q,r)=>r.json(db.prepare('SELECT * FROM continents ORDER BY name COLLATE NOCASE').all()));app.get('/api/countries',(q,r)=>r.json(db.prepare('SELECT * FROM countries WHERE (? IS NULL OR continent_code=?) ORDER BY name COLLATE NOCASE').all(q.query.continent||null,q.query.continent||null)));app.get('/api/cities',(q,r)=>{const country=q.query.country||null,minPopulation=Number(q.query.min_population||0),selectedId=Number(q.query.selected_id)||-1;r.json(db.prepare('SELECT c.*,co.name country FROM cities c JOIN countries co ON co.code=c.country_code WHERE (? IS NULL OR country_code=?) AND (population>=? OR c.id=?) ORDER BY c.id=? DESC,c.name COLLATE NOCASE LIMIT 3000').all(country,country,minPopulation,selectedId,selectedId))});app.get('/api/cities/search',(q,r)=>{const s=String(q.query.q||'').trim();if(s.length<2)return r.json([]);r.json(db.prepare("SELECT c.*,co.name country,co.continent_code FROM city_names n JOIN cities c ON c.id=n.city_id JOIN countries co ON co.code=c.country_code WHERE n.name LIKE ? ESCAPE '\\' GROUP BY c.id ORDER BY c.population DESC,c.name LIMIT 20").all(s.replace(/[\\%_]/g,'\\$&')+'%'))});
 app.get('/api/admin/users',adminOnly,(q,r)=>r.json(db.prepare("SELECT id,username,role,created_at,(SELECT COUNT(*) FROM image_viewers v WHERE v.user_id=users.id) shared_images FROM users ORDER BY username COLLATE NOCASE").all()));
 app.post('/api/admin/users',adminOnly,(q,r)=>{const username=String(q.body.username||'').trim(),password=String(q.body.password||''),role=q.body.role==='admin'?'admin':'viewer';if(!username||password.length<10)return r.status(400).json({error:'Benutzername und Passwort mit mindestens 10 Zeichen erforderlich'});try{const x=db.prepare('INSERT INTO users(username,password_hash,role) VALUES (?,?,?)').run(username,bcrypt.hashSync(password,12),role);r.status(201).json(db.prepare('SELECT id,username,role,created_at FROM users WHERE id=?').get(x.lastInsertRowid))}catch(e){if(e.code==='SQLITE_CONSTRAINT_UNIQUE')return r.status(409).json({error:'Benutzername ist bereits vergeben'});throw e}});
 app.put('/api/admin/users/:id',adminOnly,(q,r)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(q.params.id);if(!u)return r.sendStatus(404);const role=q.body.role==='admin'?'admin':'viewer';if(u.role==='admin'&&role!=='admin'&&db.prepare("SELECT COUNT(*) n FROM users WHERE role='admin'").get().n<=1)return r.status(400).json({error:'Der letzte Admin kann nicht herabgestuft werden'});const password=String(q.body.password||'');if(password&&password.length<10)return r.status(400).json({error:'Passwort muss mindestens 10 Zeichen haben'});db.prepare('UPDATE users SET role=?,password_hash=? WHERE id=?').run(role,password?bcrypt.hashSync(password,12):u.password_hash,u.id);r.json({ok:true})});
 app.delete('/api/admin/users/:id',adminOnly,(q,r)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(q.params.id);if(!u)return r.sendStatus(404);if(u.id===q.user.id)return r.status(400).json({error:'Eigenes Konto kann nicht gelöscht werden'});if(u.role==='admin'&&db.prepare("SELECT COUNT(*) n FROM users WHERE role='admin'").get().n<=1)return r.status(400).json({error:'Der letzte Admin kann nicht gelöscht werden'});db.prepare('DELETE FROM users WHERE id=?').run(u.id);r.json({ok:true})});
 app.get('/api/admin/images/:id/access',adminOnly,(q,r)=>{const image=db.prepare('SELECT id,title,visibility FROM images WHERE id=?').get(q.params.id);if(!image)return r.sendStatus(404);image.viewer_ids=db.prepare('SELECT user_id FROM image_viewers WHERE image_id=?').all(image.id).map(x=>x.user_id);r.json(image)});
 app.put('/api/admin/images/:id/access',adminOnly,(q,r)=>{if(!db.prepare('SELECT id FROM images WHERE id=?').get(q.params.id))return r.sendStatus(404);const visibility=q.body.visibility==='restricted'?'restricted':'public',ids=[...new Set((Array.isArray(q.body.viewer_ids)?q.body.viewer_ids:[]).map(Number).filter(Number.isInteger))];db.transaction(()=>{db.prepare('UPDATE images SET visibility=? WHERE id=?').run(visibility,q.params.id);db.prepare('DELETE FROM image_viewers WHERE image_id=?').run(q.params.id);const put=db.prepare('INSERT OR IGNORE INTO image_viewers(image_id,user_id) VALUES (?,?)');ids.forEach(id=>put.run(q.params.id,id))})();r.json({ok:true})});
 app.get('/api/albums',(q,r)=>r.json(db.prepare('SELECT * FROM albums ORDER BY title COLLATE NOCASE').all()));app.post('/api/albums',adminOnly,(q,r)=>{if(!q.body.title?.trim())return r.status(400).json({error:'Titel erforderlich'});const x=db.prepare('INSERT INTO albums(title,description) VALUES (?,?)').run(q.body.title.trim(),q.body.description||'');r.status(201).json(db.prepare('SELECT * FROM albums WHERE id=?').get(x.lastInsertRowid))});app.get('/api/settings',(q,r)=>r.json(Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]))));
 app.use('/vendor/leaflet',express.static(path.join(process.cwd(),'node_modules','leaflet','dist')));app.use(express.static(path.join(process.cwd(),'public')));app.get('/*splat',(q,r)=>r.sendFile(path.join(process.cwd(),'public','index.html')));app.use((e,q,r,n)=>{console.error(e);if(e.code==='LIMIT_FILE_SIZE')return r.status(413).json({error:'Datei zu groß'});r.status(500).json({error:'Interner Fehler'})});return{app,db}}
if(require.main===module){const {app}=createApp();app.listen(Number(process.env.PORT||8000),'0.0.0.0',()=>console.log(`MapLens läuft auf http://0.0.0.0:${process.env.PORT||8000}`))}module.exports={createApp};
